config/routes.rb
DaveSchaafDotCom::Application.routes.draw do
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'
  root to: 'pages#index'
  get '/resume', to: 'pages#resume'
  get '/portfolio', to: 'pages#portfolio'
  get '/running', to: 'pages#running'
  get '/travel', to: 'pages#travel'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml", "xml:lang" => "en", :lang => "en"}
  %head
    %title DaveSchaafDotCom
    %meta{name: 'viewport', content: "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag    "application", :media => "all"
    = stylesheet_link_tag    "normalize", :media => "all"
    = javascript_include_tag "application"
    %link{rel: "stylesheet", href: "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"}
    %script{src: "//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"}
    %link{rel:'stylesheet', href: 'http://fonts.googleapis.com/css?family=Roboto+Slab', type:'text/css'}
    %link{href:'http://fonts.googleapis.com/css?family=Shadows+Into+Light+Two', rel:'stylesheet', type:'text/css'}
    = stylesheet_link_tag    "main", media: "all"
    = csrf_meta_tags

%body
  %nav.navbar.navbar-default.my-nav{role: 'navigation'}
    .container-fluid
      .navbar-brand= link_to "DS", root_path
      %ul.nav.nav-justified
        %li= link_to "Resume", resume_path
        %li= link_to "Portfolio", portfolio_path
        %li= link_to "Endurance", running_path
        %li= link_to "Travel", travel_path

  = yield

app/views/pages/index.html.haml
.landing-page
  %section.panel.landing-panel
    .center-block.landing-title
      %h1 Dave Schaaf
      %h2 Don't get too comfortable
  %section.panel.quote-panel
    .center-block.quote
      %h2 "To be is to do - Socrates
      %h2  To do is to be - Sartre
      %h2  Do Be Do Be Do - Sinatra”
      %h3 ― Kurt Vonnegut
  %footer.panel
    %p I like turtles

app/views/pages/portfolio.html.haml
Portfolio

app/views/pages/resume.html.haml
%section.resume-section.container-fluid
  %h3 Education & Training
  .row
    .resume-company.col-xs-8 Dev Bootcamp
    .resume-date.col-xs-4 2014
  .row
    %ul.resume-content.col-xs-12
      %li.resume-bullet Led team of 3 students to build location-based photo sharing app in 7 days as capstone project
  .row
    .resume-company.col-xs-8 Northwestern University
    .resume-date.col-xs-4 2008
  .row
    %ul.resume-content.col-xs-12
      %li.resume-bullet B.A. in Mathematical Methods in the Social Sciences and Economics

%section.resume-section.container-fluid
  %h3 Skills & Knowledge
  .row
    %ul.resume-content.col-xs-12
      %li.resume-bullet Languages - Ruby, JavaScript, HTML, CSS, SQL
      %li.resume-bullet Frameworks - Rails, Sinatra, PhoneGap
      %li.resume-bullet Testing - RSpec, Jasmine, Capybara
      %li.resume-bullet Design - Object Orientation, Model-View-Controller
      %li.resume-bullet Tools - Object-relational databases, jQuery, Ajax, Git, Heroku, Firebase
      %li.resume-bullet Development Practices - Git workflow, Agile development, Pair programming

%section.resume-section.container-fluid
  %h3 Projects
  .row
    .resume-company.col-xs-8 Sugarsnap
    %ul.resume-content.col-xs-12
      %li.resume-bullet Share photos with the people around you based on your location
      %li.resume-bullet Track places your visited recently to see what is going on in your world
      %li.resume-bullet Moved Sugarsnap to iOS using PhoneGap


%section.resume-section.container-fluid
  %h3 Professional Experience
  .row
    .resume-company.col-xs-8 Cisco Systems, Inc.
    .resume-date.col-xs-4 July 2011-January 2014
  .row
    .resume-title.col-xs-7 Associate, Corporate Development
    .resume-location.col-xs-5 Singapore; Banglalore, India
  .row
    %ul.resume-content.col-xs-12
      %li.resume-bullet Vetted prospective investments to assess market, technology, and business model
      %li.resume-bullet Sourced investment opportunities from market research, industry partners, and cold calls
      %li.resume-bullet Organizated presentation of 2 investments to Investment Review Board
  .row
    .resume-title.col-xs-9 Associate, Corporate Development
    .resume-location.col-xs-3 San Jose, CA
  .row
    %ul.resume-content.col-xs-12
      %li.resume-bullet Led valuation of potential acquisitions in security, cloud, and core networking
      %li.resume-bullet Performed technical, financial, and operating due diligence on live transactions
      %li.resume-bullet Audited Security group operations including product management, engineering, and sales
  .row
    .resume-company.col-xs-8 J.P. Morgan Securities LLC
    .resume-date.col-xs-4 July 2008-June 2011
  .row
    .resume-title.col-xs-9 Analyst, Investment Banking
    .resume-location.col-xs-3 Chicago, IL
  .row
    %ul.resume-content.col-xs-12
      %li.resume-bullet Executed 25 capital markets transactions raising over $12 billion of capital for clients
      %li.resume-bullet Constructed operating and merger models to inform financial and strategic analysis
      %li.resume-bullet Synthesized market and company data across multiple industries for client upresume-dates and presentations

%section.resume-section.container-fluid
  %h3 Selected Acquisitions & Other Transactions
  .row
    .resume-company.col-xs-8 Cisco Systems, Inc.
    .resume-date.col-xs-4 July 2011-January 2014
  .row
    %ul.resume-content.col-xs-12
      %li.resume-bullet Sourcefire: Established Security group’s three-year operating plan and acquisition strategy
      %li.resume-bullet Cognitive Security: Determined valuation by constructing financial model from due diligence
      %li.resume-bullet Clear Access: Developed business case and wrote comunications messaging
  .row
    .resume-company.col-xs-8 J.P. Morgan Securities LLC
    .resume-date.col-xs-4 June 2008-June 2011
  .row
    %ul.resume-content.col-xs-12
      %li.resume-bullet The Mosaic Company: Split-off and orderly distribution of Cargill’s 64% stake
      %li.resume-bullet UAL Corporation: Merger of United Airlines with Continental Airlines
      %li.resume-bullet TRW Automotive: Raised $1.3 billion of captial and liquidity through four equity offerings

app/views/pages/running.html.haml
%table.table.table-striped.table-condensed
  %thead
    %tr
      %th Date
      %th League
      %th Location
      %th Race
      %th Distance (miles)
      %th Elevation (ft)
      %th Time
      %th Min/Mile
  %tr
    %td 2011-08-13
    %td PCTR
    %td Jenner, CA
    %td Salt Point
    %td 16.2
    %td 2,308
    %td 3:48:40
    %td 0:14:06
  %tr
    %td 2011-09-10
    %td Lake of the Sky
    %td Lake Tahoe, CA
    %td Lake of the Sky
    %td 18.0
    %td 2,500
    %td 4:47:57
    %td 0:15:59
  %tr
    %td 2011-10-09
    %td Marathon Majors
    %td Chicago, IL
    %td Chicago Marathon
    %td 26.2
    %td 100
    %td 4:51:08
    %td 0:11:06
  %tr
    %td 2011-10-29
    %td Ultrarunner.net
    %td Pollock Pines, CA
    %td Jenkinson Lake Fall Trail Run
    %td 17.0
    %td 2,337
    %td 3:37:03
    %td 0:12:4  %tr
    %td 2011-11-19
    %td GORUCK
    %td San Francisco, CA
    %td Class 085
    %td 15.5
    %td NA
    %td 14:00:00
    %td 0:54:1  %tr
    %td 2011-12-10
    %td Coastal Trail Runs
    %td Muir Beach, CA
    %td Coyote Ridge
    %td 20.5
    %td 4,390
    %td 4:41:03
    %td 0:13:42
  %tr
    %td 2012-01-07
    %td Coastal Trail Runs
    %td Woodside, CA
    %td Crystal Springs
    %td 26.2
    %td 3,790
    %td 6:44:57
    %td 0:15:27
  %tr
    %td 2012-02-05
    %td NA
    %td San Francisco, CA
    %td KP SF Half Marathon
    %td 13.1
    %td (100)
    %td 1:59:08
    %td 0:09:05
  %tr
    %td 2012-02-25
    %td Inside Trail Racing
    %td Castro Valley, CA
    %td Lake Chabot Trail Run
    %td 18.6
    %td 2,800
    %td 3:27:35
    %td 0:11:09
  %tr
    %td 2012-05-05
    %td Santa Rosa Cycling Club
    %td Santa Rosa, CA
    %td Wine Country Century
    %td 100.0
    %td 3,300
    %td 8:00:00
    %td 0:04:48
  %tr
    %td 2012-06-02
    %td PCTR
    %td Clayton, CA
    %td Mt Diablo Marathon
    %td 26.2
    %td 7,898
    %td 7:17:05
    %td 0:16:40
  %tr
    %td 2012-06-23
    %td Coastal Trail Runs
    %td Santa Cruz, CA
    %td San Lorenzo River
    %td 31.1
    %td 5,175
    %td 7:25:33
    %td 0:14:19
  %tr
    %td 2012-07-14
    %td Coastal Trail Runs
    %td Rodeo Beach, GGNRA, CA
    %td Golden Gate
    %td 18.6
    %td 3,900
    %td 3:31:48
    %td 0:11:23
  %tr
    %td 2012-08-04
    %td Inside Trail Racing
    %td Santa Cruz, CA
    %td San Lorenzo River
    %td 18.6
    %td 3,100
    %td 4:19:14
    %td 0:13:56
  %tr
    %td 2012-08-18
    %td Eagle Cycling Club
    %td Yountville, CA
    %td Tour of Napa
    %td 100.0
    %td 5,000
    %td 7:30:00
    %td 0:04:30
  %tr
    %td 2012-09-09
    %td Inside Trail Racing
    %td Auburn, CA
    %td K2 Summit
    %td 21.2
    %td 2,850
    %td 4:25:28
    %td 0:12:31
  %tr
    %td 2012-09-15
    %td PCTR
    %td Rodeo Beach, GGNRA, CA
    %td Headlands Hundred
    %td 26.2
    %td 5,017
    %td 5:01:35
    %td 0:11:30
  %tr
    %td 2012-10-07
    %td Marathon Majors
    %td Chicago, IL
    %td Chicago Marathon
    %td 26.2
    %td 100
    %td 3:48:01
    %td 0:08:42
  %tr
    %td 2012-11-09
    %td Coastal Trail Runs
    %td Castro Valley, CA
    %td Lake Chabot Trail Run
    %td 13.1
    %td 1,210
    %td 2:25:51
    %td 0:11:08
  %tr
    %td 2012-12-08
    %td Coastal Trail Runs
    %td Muir Beach, CA
    %td Coyote Ridge
    %td 27.3
    %td 6,250
    %td 5:44:21
    %td 0:12:36
  %tr
    %td 2012-12-15
    %td Inside Trail Racing
    %td Woodside, CA
    %td Woodside Ramble
    %td 32.0
    %td 4,700
    %td 6:20:23
    %td 0:11:53
  %tr
    %td 2013-02-16
    %td Brazen Racing
    %td Fremont, CA
    %td Bay Breeze
    %td 6.3
    %td 94
    %td 0:55:03
    %td 0:08:44
  %tr
    %td 2013-04-13
    %td Moshan Productions
    %td Los Gatos, CA
    %td Go Green Saint Patrick’s Day Run
    %td 13.1
    %td 250
    %td 2:07:45
    %td 0:09:45
  %tr
    %td 2013-04-13
    %td Inside Trail Racing
    %td Woodside, CA
    %td Woodside Ramble
    %td 22.2
    %td 3,100
    %td 5:42:29
    %td 0:15:25
  %tr
    %td 2013-04-20
    %td Zoom Running Events
    %td Ayala Cove, Angel Island State Park, CA
    %td Ayala Cove
    %td 15.0
    %td 1,840
    %td 3:32:35
    %td 0:14:10
  %tr
    %td 2013-04-28
    %td Big Sur International Marathon
    %td Big Sur Carmel, CA
    %td Big Sur International Marathon
    %td 26.2
    %td 1,660
    %td 4:41:43
    %td 0:10:45
  %tr
    %td 2013-08-02
    %td Inside Trail Racing
    %td Santa Cruz, CA
    %td San Lorenzo River
    %td 13.7
    %td 2,425
    %td 3:08:18
    %td 0:13:44

app/views/pages/travel.html.haml
%script{type:"text/javascript" src:"https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_API']}&sensor=false"}